### ISSUE TITLE
DEPLOY METHOD 😅

### ISSUE THREAD

**Issue by Castlevnia1** [EternityBots/Nezuko#11]
Please add heroku support

**Comment by RaySenpai69** [comment]
Ok let I will try it tomorrow

**Comment by RaySenpai69** [comment]
I am having issues with build pack wait one more week

**Comment by RaySenpai69** [comment]
@pratyush4932 @AliAryanTech tell me latest build pack for heroku 22 🥲

**Comment by RaySenpai69** [comment]
Done
